#!/bin/sh
# Restore for 'Backup Ubuntu Device Script'
#
# Goal: restoring previous backups
# Assumptions:
#  * Device has either ssh enabled or is at least in developer mode
#  * This machine has an ssh key which is on the mobile device


get_time() {
  date=$(echo $1 | cut -c1-4)
  date="$date.$(echo $1 | cut -c5-6)"
  date="$date.$(echo $1 | cut -c7-8)"
  date="$date $(echo $1 | cut -c10-11)"
  date="$date:$(echo $1 | cut -c12-13)"
  date="$date:$(echo $1 | cut -c14-15)"
  echo $date
}

get_id() {
  curr_id=$(echo $(ls $1/*.tgz) | cut -d'/' -f3 | cut -d'.' -f1)
}

examine_backup() {
  # show backupdate
  get_time $(echo $1 |cut -d'/' -f2 )
  # TODO show time it took to back this up

  #show device typ and id
  get_id $1
  echo "  TypeID: $(echo $curr_id |cut -d'-' -f1 )"
  echo "  Device: $(echo $curr_id |cut -d'-' -f2 )"

  # show amount of apps
  app_amount="$(wc -l < "$1"/clicks.list)"
  echo "  Apps:   $app_amount"
  # show size
  backup_size="$(du -h  "$1" | cut -f1)"
  echo "  Size:   $backup_size"
}


list_backups() {
  for i in backup/*
  do
    examine_backup $i
  done
}

list_backups
